Main/urls.py
from django.contrib import admin
from django.conf.urls import url

from django.urls import path,include
from django.contrib.auth import views as auth_views
from account.views import LoginView, RegisterView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls',namespace='account')),
    path('ticket/', include('ticket.urls',namespace='ticket')),
    path('', include('django.contrib.auth.urls')),  
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register')  
]

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views

from . import views
app_name = 'account'
urlpatterns = [   
    path('dashboard',view=views.dashboard, name='dashboard'),    
    path('check_register',view=views.check_register, name='check_register'),
    path('check_login',view=views.check_login, name='check_login'),
   
    path('',view=views.index, name='index'),
    path('logout',view=views.logout, name='logout'),
          
    
]

ticket/urls.py
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views

from . import views
app_name = 'ticket'
urlpatterns = [                   
    path('dashboard',view=views.dashboard, name='dashboard'),
    path('create',view=views.create, name='create'),
    path('edit/<str:id>',view=views.edit, name='edit'),
    # ajax
    path('store',view=views.store, name='store'),
    path('get_tickets',view=views.get_tickets, name='get_tickets'),
    path('delete',view=views.delete, name='delete'),
    path('send_link',view=views.send_link, name='send_link'),
    path('get_location_response',view=views.get_location_response, name='get_location_response'),
    path('get_location',view=views.get_location, name='get_location'),
    
]

content/templates/authroot.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="icon" type="image/png" href="{% static 'images/fav.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/intlTelInput.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>    
    <script type="text/javascript" src="{% static 'js/intlTelInput.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sweetalert2.js' %}"></script>
</head>

<body>
    <div class="login-bg">
        <div class="login-bg-inner">
            <div class="row h-100 align-items-center">               
                <div class="col-lg-12">
                  {% block content %}
                  {% endblock %}
                </div>
            </div>
        </div>
    </div>
   <div class="process-comm" id="loading">
      <div class="spinner">
         <div class="bounce1"></div>
         <div class="bounce2"></div>
         <div class="bounce3"></div>
      </div>
   </div>
    <!-- core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
   
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>

</body>

</html>

content/templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-touch">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	<title>Tickets</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
</head>

<body>

	<div class="wrapper">
		<header>
			<div class="container">
				<div class="header-data">
					<div class="logo">
						<a href="/" title="">
							<img src="{% static 'images/logo.png' %}" alt="">
						</a>
					</div>
					<!--logo end-->
					<div class="search-bar">
						<form>
							<input type="text" name="search" placeholder="Search...">
							<button type="submit"><i class="fa fa-search"></i></button>
						</form>
					</div>
					<!--search-bar end-->
					<nav class="">
						<ul>
							<li>
								<a href="{% url 'ticket:dashboard' %}" class="{% if nav and nav == 'ticket' %} selected_nav {% endif %}" title="">
									<span><i class="fas fa-bolt"></i></span>
									Tickets
								</a>
							</li>
							<li>
								<a href="" title="">
									<span><i class="fas fa-file"></i></span>
									Reports
								</a>
							</li>
							<li>
								<a href="" title="">
									<span><i class="fas fa-users"></i></span>
									Contacts
								</a>
							</li>
							
							
						</ul>
					</nav>
					<!--nav end-->
					<div class="menu-btn">
						<a href="#" title=""><i class="fa fa-bars"></i></a>
					</div>
					<!--menu-btn end-->
					<div class="user-account">
						<div class="user-info">							
							<a href="#" title="">{{ user.username }}</a>
							<i class="fa fa-sort-down"></i>
						</div>
						<div class="user-account-settingss" id="users" style="display: none;">
							<ul class="us-links">
								<li><a href="#" title="">Profile</a></li>								
							</ul>
                     <h3 class="tc">                        
                        <a class="dropdown-item" href="javascript:{document.getElementById('logout').submit()}">
                           <span>
                              <svg aria-hidden="true" style="width: 15px;height:15px;" focusable="false" data-prefix="fal" data-icon="sign-out" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="svg-inline--fa fa-sign-out fa-w-16 fa-3x"><path fill="currentColor" d="M48 64h132c6.6 0 12 5.4 12 12v8c0 6.6-5.4 12-12 12H48c-8.8 0-16 7.2-16 16v288c0 8.8 7.2 16 16 16h132c6.6 0 12 5.4 12 12v8c0 6.6-5.4 12-12 12H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48zm279 19.5l-7.1 7.1c-4.7 4.7-4.7 12.3 0 17l132 131.4H172c-6.6 0-12 5.4-12 12v10c0 6.6 5.4 12 12 12h279.9L320 404.4c-4.7 4.7-4.7 12.3 0 17l7.1 7.1c4.7 4.7 12.3 4.7 17 0l164.5-164c4.7-4.7 4.7-12.3 0-17L344 83.5c-4.7-4.7-12.3-4.7-17 0z" class=""></path></svg>
                           </span>
                           Logout
                        </a>
                        <form method="post" action="{% url 'account:logout' %}" id="logout">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>
                     </h3>                     
						</div>
						<!--user-account-settingss end-->
					</div>
				</div>
				<!--header-data end-->
			</div>
		</header>
		<!--header end-->

		<main>
         {% block content %}
            
         {% endblock %}			
		</main>
	</div>
	<div class="process-comm" id="loading">
		<div class="spinner">
		   <div class="bounce1"></div>
		   <div class="bounce2"></div>
		   <div class="bounce3"></div>
		</div>
	 </div>
	<!--theme-layout end-->

	
	<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/owl.carousel.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/sweetalert2.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>


</body>

</html>